### ISSUE TITLE
Multiple URL's refer to the same html after build

### ISSUE THREAD

**Issue by spatrame** [MindtreePGSSG/ModernWeb#2]
Can we have multiple URL's to the same html page.
Below is the one of the URL -
http://sample.domain.com/article/summer-article
And, I wants to have a tiny url as well which should refer to the same html page.
http://sample.domain.com/new-article

Is there any way to add route path without creating multiple HTML page. Can I refer two urls to the same page in gatsby?

Issue raised earlier: gatsbyjs/gatsby#1076

**Comment by KyleAMathews** [comment]
Answered in https://github.com/gatsbyjs/gatsby/issues/1076
