### ISSUE TITLE
Regarding the toml-loader package

### ISSUE THREAD

**Issue by ajeeshadressary** [MindtreePGSSG/ModernWeb#4]
Is there any restriction that the toml-loader will parse only from config.toml file.I have tried the loader with toml files with other filename like(sample.toml or test.toml) but it end up with errors.

**Comment by KyleAMathews** [comment]
There isn't a toml-loader setup by default in Gatsby 1.0 actually. I can create a `gatsby-plugin-toml`  package and add this to the project though to add support for this.
