### ISSUE TITLE
filter with local data to allContentfulBrandExperience 

### ISSUE THREAD

**Issue by spatrame** [MindtreePGSSG/ModernWeb#7]
How can I add filter with node_local data to below graphql query.

>   allContentfulBrandExperience {
>             edges {
>               node {
>                 node_locale
>                 slug
>               }
>             }
>           }

**Comment by KyleAMathews** [comment]
Check out the code for the example app — https://using-contentful.gatsbyjs.org/

https://github.com/gatsbyjs/gatsby/blob/1.0/examples/using-contentful/src/pages/index.js#L82
