### ISSUE TITLE
responsiveResolution graphql-contentful not handling gif images

### ISSUE THREAD

**Issue by spatrame** [MindtreePGSSG/ModernWeb#8]
Below Graphql query is not handling gif images. 

>   responsiveResolution {
>           src
>           srcSet
>           width
>           height
>         }

**Comment by spatrame** [comment]
If we use responsiveResolution in graphql query while gatsby build it is returning null.

**Comment by KyleAMathews** [comment]
Sorry for the delay in fixing these — was occupied today on preparing a new beta release for Gatsby. Will fix these bugs in the morning.

**Comment by spatrame** [comment]
Reference url : http://localhost:8000/en-us/the-downy-fabric-conditioner-difference/fabric-protection

**Comment by KyleAMathews** [comment]
Fixed in latest beta

![screen shot 2017-07-01 at 10 56 36 pm](https://user-images.githubusercontent.com/71047/27767587-919bfbf2-5eb0-11e7-98d4-117ca464620f.png)

**Comment by KyleAMathews** [comment]
https://github.com/MindtreePGSSG/ModernWeb/pull/11
