### ISSUE TITLE
URL refresh issue

### ISSUE THREAD

**Issue by spatrame** [MindtreePGSSG/ModernWeb#9]
below page refresh is working
http://localhost:8000/en-us/the-downy-fabric-conditioner-difference/fabric-protection/

but if we remove  last character / from the url, refresh page is not working
http://localhost:8000/en-us/the-downy-fabric-conditioner-difference/fabric-protection

**Comment by KyleAMathews** [comment]
Fixed by https://github.com/MindtreePGSSG/ModernWeb/pull/11
